//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosAlmacen.Usuario
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UsuariosEntities3 : DbContext
    {
        public UsuariosEntities3()
            : base("name=UsuariosEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<V_USUARIOS_PERFILES> V_USUARIOS_PERFILES { get; set; }
    
        public virtual int PA_CREAR_USUARIO(string uSUARIO, string pASSWORD, Nullable<int> pERFIL, string eMAIL, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var pERFILParameter = pERFIL.HasValue ?
                new ObjectParameter("PERFIL", pERFIL) :
                new ObjectParameter("PERFIL", typeof(int));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_CREAR_USUARIO", uSUARIOParameter, pASSWORDParameter, pERFILParameter, eMAILParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_LOGIN(string eMAIL, string pASSWORD, ObjectParameter iD_USUARIOS, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_LOGIN", eMAILParameter, pASSWORDParameter, iD_USUARIOS, rETCODE, mENSAJE);
        }
    
        public virtual int PA_BORRAR_USUARIO(Nullable<int> iD_USUARIO, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_BORRAR_USUARIO", iD_USUARIOParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_MODIFICAR_USUARIO(Nullable<int> iD_USUARIO, string uSUARIO, string pASSWORD, Nullable<int> pERFIL, string eMAIL, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var pERFILParameter = pERFIL.HasValue ?
                new ObjectParameter("PERFIL", pERFIL) :
                new ObjectParameter("PERFIL", typeof(int));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MODIFICAR_USUARIO", iD_USUARIOParameter, uSUARIOParameter, pASSWORDParameter, pERFILParameter, eMAILParameter, rETCODE, mENSAJE);
        }
    }
}
