//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosAlmacen.Articulos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULOS()
        {
            this.PEDIDOS_ARTICULOS = new HashSet<PEDIDOS_ARTICULOS>();
        }
    
        public int ID_ARTICULO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string FABRICANTE { get; set; }
        public decimal PESO { get; set; }
        public Nullable<decimal> ALTO { get; set; }
        public Nullable<decimal> LARGO { get; set; }
        public Nullable<decimal> ANCHO { get; set; }
        public decimal PRECIO { get; set; }
        public byte[] IMAGEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDOS_ARTICULOS> PEDIDOS_ARTICULOS { get; set; }
        public virtual STOCK STOCK { get; set; }
    }
}
