//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosAlmacen.Articulos
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        public int ID_ARTICULO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    
        public virtual ARTICULOS ARTICULOS { get; set; }
    }
}
