//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosAlmacen.Articulos
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ARTICULOS_STOCK
    {
        public string NOMBRE { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string DESCRIPCION { get; set; }
        public string FABRICANTE { get; set; }
        public decimal PESO { get; set; }
        public Nullable<decimal> ALTO { get; set; }
        public Nullable<decimal> LARGO { get; set; }
        public Nullable<decimal> ANCHO { get; set; }
        public decimal PRECIO { get; set; }
        public byte[] IMAGEN { get; set; }
        public int ID_ARTICULO { get; set; }
    }
}
